# encoding: utf-8

source 'https://rubygems.org'

gem 'sinatra'
gem 'eventmachine', '= 1.0.6'
gem 'thin', '= 1.6.3'
gem 'thor', git: 'https://github.com/erikhuda/thor.git'

group :ignore do
  gem 'rack-test'
end
